### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by casperdcl**
- Enables `pip install`
- replaces/closes #573 by renaming package `pydcm2niix` => `dcm2niix` thanks to pypa/pypi-support#1609

### CODE REVIEW

**Comment by ningfei** [comment]
Looks good to me. Only one thing: is `cmake_args=[f"-DCM2NIIX_BUILD_VERSION={build_ver}", "-DBUILD_ALL_DEP=ON"])` needed for the python package? Since we don't have the two options in the SuperBuild.cmake.  Besides, there's a typo here: `-DCM2NIIX_BUILD_VERSION={build_ver}` should be `-DDCM2NIIX_BUILD_VERSION={build_ver}`.

**Comment by neurolabusc** [comment]
@casperdcl can you respond to @ningfei 's comments. I am eager to push a belated spring release.

**Comment by casperdcl** [comment]
Sorry for the delay @neurolabusc @ningfei, just pushed some changes.

- `BUILD_ALL_DEP`: good catch, this was leftover from a different project unrelated to dcm2niix
- `DCM2NIIX_BUILD_VERSION`: indeed, missing a `D` prefix. It's usually nice to define this sort of thing for external C-libraries to potentially use, but I agree probably not worth it seeing as `dcm2niix` doesn't currently us it.

**Comment by casperdcl** [comment]
Hey @neurolabusc is this good to go now? fyi #601 is still a problem on CentOS systems but according to discussion there you're fixing it next release?

**Comment by neurolabusc** [comment]
@ningfei can you merge this if you are happy with this. I am overdue for a new stable release, but I am waiting for a bit more feedback on [XA30 conversion](https://github.com/neurolabusc/dcm_qa_xa30).

**Comment by ningfei** [comment]
sure!

**Comment by casperdcl** [comment]
Hey @ningfei @neurolabusc - despite being merged, the changes from this PR don't appear to be anywhere in [development](https://github.com/rordenlab/dcm2niix/tree/development) and/or [master](https://github.com/rordenlab/dcm2niix/tree/master)

**Comment by neurolabusc** [comment]
@ningfei this seems to be in your area of expertise. Tell me if you are too busy to address this.

**Comment by neurolabusc** [comment]
@ningfei I would be happy to update the master to create a new stable release. However, both issues [629](https://github.com/rordenlab/dcm2niix/issues/629) and [647](https://github.com/rordenlab/dcm2niix/issues/647) seem to fall in your expertise. Would you please respond to each of those (even if it is just to acknowledge them) prior to updating the master branch.

**Comment by ningfei** [comment]
@neurolabusc  will have a look soon. For the CI, probably I will still use AppVeyor for now. Since Github Actions doesn't support _old_ images like  Ubuntu 16.04 or macOS Cataline.

**Pull request merged**
