### PR TITLE
dcm2niix_fswrapper

### PR DESCRIPTION
**Pull request by yhuang43**
1. Implement a wrapper class to interface with dcm2niix functions.
    2. The wrapper class provides interface to convert dicom in mgz orientation.
    3. The wrapper class and dcm2niix functions are compiled into libdcm2niixfs.a
       with -DUSING_DCM2NIIXFSWRAPPER -DUSING_MGH_NIFTI_IO.
    4. When using libdcm2niixfs.a, instead of outputting .nii, *.bval, *.bvec to disk,
       nifti header, image data, TDICOMdata, & TDTI information are saved in MRIFSSTRUCT struct.
    5. If libdcm2niixfs.a is compiled with -DUSING_MGH_NIFTI_IO, the application needs to link with nifti library.

### CODE REVIEW

**Comment by neurolabusc** [comment]
Thanks. This looks good. @ningfei do you have any comments?

**Comment by ningfei** [comment]
Hi @yhuang43  thanks for the update! The compiling goes through now.

1. Have you already tested it with JPEG2000 compressed DICOMs to see if the decoding really works? `target_link_libraries` may only work for executables. If you check the final generated `libdcm2niixfs.a`, those optional libs seems not really compiled into it (correct me if I'm wrong here). You may need to use `ar` to combine those libs. So when an executable links to `libdcm2niixfs.a`, it already has all the dependencies included.
2. You may want to add an `install` command (for example `install(TARGETS ${DCM2NIIXFSLIB} DESTINATION lib)` ) in the CMake file to put the compiled lib in `lib` folder.
3. You may also want to add a control option in the CMake file to let the user choose if they want to additionally build the lib and can set it to `OFF` by default.

Only a side note, I usually `rebase` my local branch onto remote upstream instead of `merge` from upstream before I create a PR. Thus the PR will have a linear commit history without those `Merge branch XXXX` commits. It's more clearer and easy to see what's going on in the PR imho.

**Comment by neurolabusc** [comment]
@yhuang43 if you want to test JPEG2000, a couple samples are included in the [dcm_qa](https://github.com/neurolabusc/dcm_qa/tree/master/In/Orientation/axmb/AxInt36mb) validation repository. As I describe [here](https://crnl.readthedocs.io/jpeg_formats/index.html) you can use gdcmconv  to convert your own DICOMs to JPEG-LS (`gdcmconv -L in.dcm out.dcm`) and JPEG-2K (`gdcmconv -K in.dcm out.dcm`). 

Alternatively, you may simply want to not support JPEG2000 DICOMs for conversion. The format saw very little adoption: for photography it was outclassed by HEIF, for lossy DICOM the tendency for high compressions ratios to lead to subtle smeariness versus classic-JPEG blockiness is not an asset (e.g. a radiologist looks for loss of distinct borders in hippocampus), and the lossless performance leads to slightly poorer compression ratios and much [slower performance](https://crnl.readthedocs.io/jpeg_formats/index.html) than the simpler JPEG-LS. The Jasper JPEG2000 library has issues with 16-bit data, so OpenJPEG is the only viable open source library. While it is robust, it is not designed for speed and in my experience the incompatible API forks for tools like gdcm versus the default library do cause issues with dynamic linking. 

In my experience, the ancient lossless JPEG is the most common lossless DICOM seen in the wild, and dcm2niix handles this internally without any libraries. The more recent JPEG-LS and JPEG-2K are exceptionally rare. I think this reflects the fact that it is not supported in the free versions of dcmtk. The only popular tools I know of that generate JPEG-2K are Osirix and Horos.   

Thanks @ningfei for your insights - both on CMake and on clean PRs.

**Comment by yhuang43** [comment]
@ningfei You are right about libdcm2niixfs.a. It doesn't include the dependencies. If I build it as a shared library libdcm2niixfs.so, target_link_libraries brings in all the dependencies.

**Comment by ningfei** [comment]
@yhuang43 yes, that's also what I wanted to ask. Do you think `libdcm2niixfs` will mainly be used as a static lib or a shared lib? Guess a static lib would be more conveneint to link against? I also agree with Chris that you may also choose not to support those optional external libs used in dcm2niix.

**Comment by ningfei** [comment]
Hi @yhuang43 thank you very much for the update. Looks good to me now. I will check it out locally and then merge it.

**Comment by ningfei** [comment]
Hi @yhuang43 I refined the CMake files and created a new PR #562 based on your commits. Now everything should work. I'm going to close this one. Will merge the new PR into development branch if Chris also agrees.

**Comment by yhuang43** [comment]
Thank you so much!

________________________________

**Comment by neurolabusc** [comment]
I concur. Please merge.

**Pull request closed without merging**
