### PR TITLE
Respect pixel padding value during interpolation

### PR DESCRIPTION
**Pull request by alund**
* Fixes https://github.com/rordenlab/dcm2niix/issues/262

### CODE REVIEW

**Comment by neurolabusc** [comment]
This looks clear. Can I make one request: instead of four variables
  isHasPixelPaddingValue
  isHasFloatPixelPaddingValue
  pixelPaddingValue
  floatPixelPaddingValue
Could we have just
   floatPixelPaddingValue
that is set to NAN by default? The structure TDICOMdata is required for each and every DICOM, so keeping these smaller is better. For the case of 16-bit data you can just use the specify pixelPaddingValue = round(floatPixelPaddingValue) in nii_saveNII3Dtilt(). And isHasPixelPaddingValue can be set in nii_saveNII3Dtilt() and nii_saveNII3DtiltFloat32() based on whether floatPixelPaddingValue == NAN.

**Comment by alund** [comment]
I have pushed a new commit that makes this change. It also fixes a mistake I made: the data type for Float Pixel Padding Value is FL and so should have been read with `dcmFloat()` not `dcmStrFloat()`. I also realized that, if a pixel padding value is defined, it should be used for the padding done in `nii_saveNII3Dtilt()` and `nii_saveNII3DtiltFloat32()`.

Having done all of that, I would like to do some more testing before you merge this. Feel free to review, but even if you have no more comments, I would appreciate it if you wait before merging until I have confirmed that my additional testing is complete.

**Comment by neurolabusc** [comment]
Looks good to me. I will hold off until I get your OK.

**Comment by alund** [comment]
The tests I have run so far have been fine. I think you can go ahead and merge. Obviously if I find anything later, I'll fix it and submit another pull request.

**Pull request merged**
