### PR TITLE
Fix for MSVC

### PR DESCRIPTION
**Pull request by ningfei**

### CODE REVIEW

**Comment by neurolabusc** [comment]
I have incorporated the "and" -> "&&" fix, but the strtok is no longer required (was not available for mingw compiler). Could you please test the latest master using MSVC and we can close this if it works. Thanks again for your help.

**Comment by ningfei** [comment]
It works now. And thank you for the link about the "and" alias.

**Comment by ningfei** [comment]
Hi Chris,

I just tested it. The latest master works well with MSVC (tested with MSVC
14.0). The PR can be closed now.

Best,
Ningfei

**Comment by chrisfilo** [comment]
Hi Ningfei - as an expert in VIsual Studio maybe you could help us configure Appveyor config (it's a continuous integration service that - in theory - will check if dcm2niix compiles with VS on each commit and PR). I tried to do it, but I lack the experience. The file is here: https://github.com/rordenlab/dcm2niix/blob/master/appveyor.yml

**Comment by ningfei** [comment]
Hi Chris, will try to do it this weekend.

**Pull request closed without merging**
