### PR TITLE
Improving support for big-endian systems

### PR DESCRIPTION
**Pull request by jonclayden**
I've recently created [`divest`](https://github.com/jonclayden/divest), a fork of `dcm2niix` packaged for R, and since published R packages are [automatically tested](https://cran.r-project.org/web/checks/check_results_divest.html) on several platforms the code gets exercised quite well. One thing that came up is that on SPARC/Solaris, a big-endian platform, `divest` was producing segfaults. I traced this to the code for reading CSA blocks, which are always stored little endian, but whose elements weren't previously byte-swapped.

In this PR I'm including some edits to byte-swap elements of the CSA-related `struct`s that are subsequently used by the code. I also check system endianness more robustly, rather than relying on the `__BIG_ENDIAN__` constant, which [isn't always defined](https://sourceforge.net/p/predef/wiki/Endianness/). (There should be no real overhead for this, since the compiler should optimise the `littleEndianPlatform` function out of existence.) With these changes the segfaults do seem to be resolved.

### CODE REVIEW

**Comment by ghisvail** [comment]
Isn't the `__BYTE_ORDER` macro sufficient? See [here](https://sourceforge.net/p/predef/wiki/Endianness/) for details.

**Comment by jonclayden** [comment]
I [get the impression](http://stackoverflow.com/a/27054190) that no single macro or constant suffices for all OS/compiler combinations. Testing it explicitly seems more robust and elegant to me, but it's a matter of preference.

**Comment by ghisvail** [comment]
Debian supports sparc, so looking at how endianness is handled in the Debian source code repository could help. Here are the [results](https://codesearch.debian.net/search?q=__BYTE_ORDER&perpkg=1) for a search on `__BYTE_ORDER`. `pulseaudio` works on sparc and relies on this macro only for endianness detection. Perhaps, it would be worth trying it out first, before considering a more complex solution.

**Comment by jonclayden** [comment]
But, which is more complex?

```c
if (!littleEndianPlatform())
  // byte swap
```

or

```c
#if __BYTE_ORDER == __BIG_ENDIAN
  // byte swap
```

plus the requirement to include whatever system header file defines these things, which might itself vary from platform to platform? (Debian tells us about Linux, but what about Solaris?)

This is a bit of a tempest in a teacup; I really don't have a strong opinion about how `dcm2niix` should handle this. But hopefully we can agree that segfaults are better avoided, and that is the primary aim of this PR.

**Comment by ghisvail** [comment]
> Which is more complex?

Your solution has the overhead of an additional function call to evaluate the `swap` boolean at runtime, whereas `__BYTE_ORDER` would resolve the code path at build time.

> plus the requirement to include whatever system header file defines these things

It should be documented somewhere, since these macros are widely used. I am also wondering how the endianness is handled in the Nifti encoder.

> Debian tells us about Linux, but what about Solaris?

Debian and Solaris are operating systems, Linux is a kernel and Sparc is a platform. Endianness is defined by the platform. Debian can run on `sparc`, in the same way that Solaris can run on `x86`.

**Comment by neurolabusc** [comment]
Ghislain-
  I think we have to recognize that not all compilers support a single definition for determining byte order. Jon's solution is elegant because it should work on any system. Regardless of whether it is more or less elegant, the fact that it is robust across systems is a major advantage. As Jon notes, a modern compiler will convert this into a constant and both the conditional and function call will vanish. So there is no overhead, and the readability of the code seems straight forward. I will dust off an old PowerPC OSX computer to test that this works. This will give me a chance to test Jons solution (seems like it will obviously work) and also test big endian support in general. While dcm2nii was heavily tested on that platform, I have never actually tested dcm2niix on a big-endian machine.

**Comment by ghisvail** [comment]
Le 17 déc. 2016 10:57 PM, "Chris Rorden" <notifications@github.com> a
écrit :

Ghislain-
I think we have to recognize that not all compilers support a single
definition for determining byte order. Jon's solution is elegant because it
should work on any system. Regardless of whether it is more or less
elegant, the fact that it is robust across systems is a major advantage. As
Jon notes, a modern compiler will convert this into a constant and both the
conditional and function call will vanish. So there is no overhead, and the
readability of the code seems straight forward.

Your call.

I will dust off an old PowerPC OSX computer to test that this works. This
will give me a chance to test Jons solution (seems like it will obviously
work) and also test big endian support in general. While dcm2nii was
heavily tested on that platform, I have never actually tested dcm2niix on a
big-endian machine.

You can use qemu for that.

**Pull request merged**
